# -----------------------------------------------------------------------------
# Jiacan Li - 个人网站核心配置
# -----------------------------------------------------------------------------
title: Jiacan Li
first_name: Jiacan
last_name: Li
email: jessielijc@outlook.com
description: "B.Eng. in Robotics Engineering @ SUSTech"

# ！！！强制修正路径！！！
url: https://jessielijc.github.io
baseurl: ""

# -----------------------------------------------------------------------------
# 插件设置：把那个报错的插件 (jekyll-3rd-party-libraries) 删掉
# -----------------------------------------------------------------------------
plugins:
  - jekyll-archives-v2
  - jekyll-feed
  - jekyll-sitemap
  - jemoji
  - jekyll-link-attributes

# -----------------------------------------------------------------------------
# 必须保留的基础结构 (即使是空的也要有，防止其他代码报错)
# -----------------------------------------------------------------------------
navbar_fixed: true
footer_fixed: true
max_width: 930px
enable_darkmode: true

collections:
  news:
    output: true
  projects:
    output: true

# 编译设置
markdown: kramdown
highlighter: rouge
include: ["_pages", "_scripts"]
exclude:
  - bin/
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
sass:
  style: compressed
